name: env-01
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
      - langchain==0.3.27
      - langchain-chroma==0.2.5
      - langchain-community==0.3.27
      - langchain-core==0.3.72
      - langchain-ollama==0.3.6
      - langchain-text-splitters==0.3.9
      - langsmith==0.4.8
      - ollama==0.5.1
      - pillow==11.3.0
      - pip==25.2
      - pyarrow==21.0.0
      - setuptools==80.9.0
      - streamlit
