name: env-01
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - altair=5.5.0
  - annotated-types=0.6.0
  - anyio=4.7.0
  - arrow-cpp=19.0.0
  - asgiref=3.8.1
  - async-timeout=4.0.3
  - attrs=24.3.0
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.27
  - aws-c-io=0.13.11
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - backoff=1.11.1
  - bcrypt=4.3.0
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.14
  - cachetools=5.5.1
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - chromadb=1.0.15
  - click=8.1.8
  - coloredlogs=15.0.1
  - cryptography=45.0.5
  - dataclasses-json=0.6.7
  - deprecated=1.2.13
  - distro=1.9.0
  - dnspython=2.4.2
  - durationpy=0.10
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.0
  - expat=2.7.1
  - fastapi=0.115.9
  - fastapi-cli=0.0.8
  - filelock=3.17.0
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2025.7.0
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=2.38.0
  - googleapis-common-protos=1.69.2
  - greenlet=3.1.1
  - grpcio=1.62.2
  - h11=0.16.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - httpx-sse=0.4.0
  - huggingface_hub=0.31.2
  - humanfriendly=10.0
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.0
  - importlib_resources=6.4.0
  - jinja2=3.1.6
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.20
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc=1.62.2
  - libjpeg-turbo=3.1.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libpulsar=3.5.1
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.6.0
  - libuv=1.48.0
  - libwebp-base=1.6.0
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - marshmallow=3.19.0
  - mdurl=0.1.0
  - mmh3=5.0.1
  - monotonic=1.5
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - mypy_extensions=1.0.0
  - narwhals=2.0.1
  - ncurses=6.4
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.3.1
  - onnxruntime=1.20.1
  - openjpeg=2.5.2
  - openssl=3.5.1
  - opentelemetry-api=1.35.0
  - opentelemetry-exporter-otlp-proto-grpc=1.15.0
  - opentelemetry-instrumentation=0.56b0
  - opentelemetry-instrumentation-asgi=0.56b0
  - opentelemetry-instrumentation-fastapi=0.56b0
  - opentelemetry-proto=1.15.0
  - opentelemetry-sdk=1.35.0
  - opentelemetry-semantic-conventions=0.56b0
  - opentelemetry-util-http=0.56b0
  - orc=2.0.1
  - orjson=3.10.14
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.3.1
  - posthog=3.16.0
  - propcache=0.3.1
  - protobuf=4.25.3
  - pthread-stubs=0.4
  - pulsar-client=3.5.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybase64=1.4.2
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydantic-settings=2.6.1
  - pydeck=0.9.1
  - pygments=2.19.1
  - pyopenssl=25.1.0
  - pypdf=4.2.0
  - pypika=0.48.9
  - pyproject_hooks=1.0.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-flatbuffers=24.3.25
  - python-kubernetes=32.0.1
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.4
  - requests-oauthlib=2.0.0
  - requests-toolbelt=1.0.0
  - rich=13.9.4
  - rich-toolkit=0.14.9
  - rpds-py=0.22.3
  - rsa=4.7.2
  - shellingham=1.5.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlalchemy=2.0.41
  - sqlite=3.50.2
  - starlette=0.45.3
  - streamlit=1.47.1
  - sympy=1.13.3
  - tenacity=9.0.0
  - tk=8.6.14
  - tokenizers=0.21.0
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - uvicorn=0.35.0
  - uvicorn-standard=0.35.0
  - uvloop=0.21.0
  - watchdog=6.0.0
  - watchfiles=0.24.0
  - websocket-client=1.8.0
  - websockets=15.0.1
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - langchain==0.3.27
      - langchain-chroma==0.2.5
      - langchain-community==0.3.27
      - langchain-core==0.3.72
      - langchain-ollama==0.3.6
      - langchain-text-splitters==0.3.9
      - langsmith==0.4.8
      - ollama==0.5.1
      - pillow==11.3.0
      - pip==25.2
      - pyarrow==21.0.0
      - setuptools==80.9.0
